### ISSUE TITLE
I want the group to be able to be set to a variable.

### ISSUE THREAD

**Issue by shiningstone** [Didericis/permissions-mixin#10]
I'd like to thank you guys for this brilliant package. However, I found it not so close to my expectation.
I am creating some groups, each of which includes several users and support several operations.
So method for one of the operation should defined like this
`const deleteUser = new ValidatedMethod({`
`    name: 'DeleteUser',`
`    mixins: [PermissionsMixin],`
`    allow: [{`
`        roles: ['creator'],`
`        group: {target-group},`
`        allow({target-group, target-user}) { ..... }`
`    }],`
`    validate: new SimpleSchema({`
`        target-group: { type: String },`
`        target-user: { type: String },`
`    }).validator(),`
`    run({text}) {`
`        return testCollection.insert({text: text});`
`    }`
`});`

Referring to the instruction, the group should be 'either true, a string, or an array of strings', so the code above may not function fine. Do you have any suggestions on this?

Thank you again!

**Comment by Didericis** [comment]
Thank you!

I'm not sure I understand the question, but based on what you have defined in your schema, I'm guessing you want to check if a user is allowed to be deleted based on the `target-group` field being passed to your method. If you would like to only permit that field to be equal to the group of the current user, you could define an `allow` permissions object for each of the different groups. For example, assuming you have two groups, `manchester.com` and `real-madrid.com`, and you want members of `manchester.com` to only be allowed to use the method when the `target-group` is set to `manchester.com`, and you want members of `real-madrid.com` to only be allowed to use the method when the group is set to `real-madrid.com`, you could define your method like this:

```js
const deleteUser = new ValidatedMethod({
  name: 'DeleteUser',
  mixins: [PermissionsMixin],
  allow: [{
    roles: ['creator'],
    group: `manchester.com`,
    allow(input) {
      return input['target-group'] === 'manchester.com';
    },
  }, {
    roles: ['creator'],
    group: `real-madrid.com`,
    allow(input) {
      return input['target-group'] === 'real-madrid.com'
    },
  }],
  validate: new SimpleSchema({
    'target-group': { type: String },
    'target-user': { type: String },
  }).validator(),
  run(input) {
    // do stuff with `target-group` and `target-user` inputs
  }
});
```

**Comment by Didericis** [comment]
Depending on what your objective is, another option would be to get params based on the user`s group/s within the method body instead of passing something in:

```js
const deleteUser = new ValidatedMethod({
  name: 'DeleteUser',
  mixins: [PermissionsMixin],
  allow: [{
    roles: ['creator'],
    group: true,
  }],
  validate: new SimpleSchema({
    'target-user': { type: String },
  }).validator(),
  run(input) {
    const groups = Object.keys(Meteor.user().roles);
    // do stuff with `groups` and the `target-user` input
  }
});
```

**Comment by shiningstone** [comment]
I've been working on other projects these days.
Thanks for your recommandation!
